---
- name: Deploy and configure Postgres 12
  hosts: database_servers
  become: true
  gather_facts: false
  collections:
    - community.postgresql
  tasks:

    - name: Setup firewall
      include_role:
        name: firewall
      vars:
        firewall_services:
          - postgresql

    - name: Setup PostgreSQL
      include_role:
        name: postgres
